language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ayush/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ayush/react-test npm run test

after_success:
  - docker build -t ayush/multi-client -f ./client/Dockerfile ./client
  - docker build -t ayush/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t ayush/multi-server -f ./server/Dockerfile ./server
  - docker build -t ayush/multi-worker -f ./worker/Dockerfile ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to the docker hub
  - docker push ayush/multi-client
  - docker push ayush/multi-nginx
  - docker push ayush/multi-server
  - docker push ayush/multi-worker

  # Logout of docker
  - docker logout
